version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env.prod
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
    command: yarn start:prod
    env_file:
      - .env.prod
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: